# Generated by Django 3.2.3 on 2021-06-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(blank=True, verbose_name='numero habitacion')),
                ('tipo_cama', models.CharField(blank=True, choices=[('0', 'Single'), ('1', 'Double'), ('2', 'King')], max_length=1, verbose_name='tipo de camas')),
                ('tipo_baños', models.CharField(blank=True, choices=[('0', 'Simple'), ('1', 'Medium'), ('2', 'Avanzado')], max_length=1, verbose_name='tipo de baños')),
                ('tipo_cantidad', models.CharField(blank=True, choices=[('0', 'Uno'), ('1', 'Dos'), ('2', 'Tres')], max_length=1, verbose_name='cantidad de personas por habitacion')),
            ],
        ),
    ]
