# Generated by Django 3.2.3 on 2021-06-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(blank=True, choices=[('0', 'Administrador'), ('1', 'Empleado'), ('2', 'Cliente')], max_length=1, verbose_name='Tipo usuario')),
                ('run', models.CharField(blank=True, max_length=13, verbose_name='Rol Único Nacional')),
                ('nombre', models.CharField(blank=True, max_length=20, verbose_name='Nombre del usuario')),
                ('apellido_paterno', models.CharField(blank=True, max_length=20, verbose_name='Apellido paterno del usuario')),
                ('apellido_materno', models.CharField(blank=True, max_length=20, verbose_name='Apellido materno del usuario')),
                ('sexo', models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer'), ('O', 'Otro')], max_length=1, verbose_name='Sexo usuario')),
                ('fecha_nacimiento', models.DateField(blank=True, verbose_name='Fecha nacimiento usuario')),
                ('contacto', models.PositiveIntegerField(blank=True, verbose_name='Número de contacto')),
                ('email', models.EmailField(max_length=100, verbose_name='Email del usuario')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Usuario registrado',
                'verbose_name_plural': 'Usuarios registrados',
            },
        ),
    ]
