# Generated by Django 3.2.3 on 2021-06-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210611_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha nacimiento usuario'),
        ),
    ]
